stella_v1 = {
    'None': '{prompt}',
    '3D Game': '{prompt}, isometric 3d video game design, 3d game art, isometric game art, mobile game assets, fantasy video game, mobile game, 3d epic illustration, epic video game, stylized mobile game graphics',
    'Abstract Cityscape': '{prompt} abstract cityscape, Ultra Realistic Cinematic Light abstract, futuristic, cityscape, Out of focus background and incredible 16k resolution produced in Unreal Engine 5 and Octan render',
    'Abstract Vibrant': '{prompt}, vibrant, editorial, abstract elements, colorful, color splatter, realism, Inspired by the style of Ryan Hewett, dynamic realism, soft lighting and intricate details',
    'Amazonian': '{prompt}, amazonian cave, jungle, waterfall, moss-covered ancient ruins, Dramatic lighting and intense colors, mesmerizing details of the environment and breathtaking atmosphere',
    'Anime': '{prompt}, anime atmospheric, atmospheric anime, anime character; full body art, digital anime art, beautiful anime art style, anime picture, anime arts, beautiful anime style, digital advanced anime art, anime painting, anime artwork, beautiful anime art, detailed digital anime art, anime epic artwork',
    'Aquatic': '{prompt}, graceful movement with intricate details, inspired by artists like Lotte Reiniger, Carne Griffiths and Alphonse Mucha. Dreamy and surreal atmosphere, twirling in water surface',
    'Architecture': '{prompt}, modern architecture design, luxury architecture, bright, very beautiful, trending on unsplash, breath taking',
    'Avatar': '{prompt}, avatar movie, avatar with blue skin, vfx movie, cinematic lighting, utopian jungle, pandora jungle, sci-fi nether world, lost world, pandora fantasy, high quality render',
    'Bauhaus': '{prompt} Bauhaus art movement,  by Wassily Kandinsky, bauhaus style painting, geometric abstraction, vibrant colors, painting',
    'Candyland': '{prompt}, candy land style,  whimsical fantasy art, japanese pop surrealism, colorfull digital fantasy art, made of candy and lollypops, whimsical and dreamy',
    'Chromatic': '{prompt}, (((chromatic))) vaporwave nostalgia, vaporwave artwork, ((synthwave)), chromatic colors, , 3d render, vibrant chromatic colors, glowing chromatic colors',
    'Cinematic Render': '{prompt}, cinematic, breathtaking colors, close-up, cgscociety, computer rendering, by mike winkelmann, uhd, rendered in cinema4d, surface modeling, 8k, render octane, inspired by beksinski',
    'Claymation': '{prompt} clay animation, as a claymation character, claymation style, animation key shot, plasticine, clay animation, stopmotion animation, aardman character design, plasticine models',
    'Clip Art': '{prompt}, (((clip art))), clip art illustration, cartoon character, thin black stroke outline, pastel colors, cute illustration,  vector illustration',
    'Coloring Book': '{prompt}, line art illustration, lineart behance hd, illustration line art style, line art colouring page, decora inspired illustrations, coloring pages, digital line-art, line art!!, thick line art, coloring book page, clean coloring book page, black ink line art, coloring page, detailed line art',
    'Comic Book': '{prompt}, Comic cover, 1960s marvel comic, comic book illustrations',
    'Comic V2': '{prompt}, comic book, john romita senior, inspired by Alton Tobey, by Alan Davis, arachnophobia, by Alton Tobey, as a panel of a marvel comic, marvel comic',
    'Cosmic': '{prompt}, in cosmic atmosphere, humanitys cosmic future,  space art concept, scene in space, cosmic space, beautiful space star planet, background in space, realistic, cinematic, breathtaking view',
    'Crayon Art': '{prompt}, crayon drawing, inspired by Louis Valtat, inspired by Gabriele Münter, oil pastels, crayon on paper, crayon texture, crayon illustration, drawing done with crayons, pastel colors',
    'Cubism': '{prompt} cubist picasso, cubism,  a cubist painting, heavy cubism, cubist painting, by Carlo Carrà, style of picasso, modern cubism, futuristic cubism',
    'Cyberpunk': '{prompt}, synthwave image, (neotokyo), dreamy colorful cyberpunk colors, cyberpunk blade runner art, retrofuturism, cyberpunk, beautiful cyberpunk style, cgsociety 9',
    'Disney': '{prompt}, disney animation, disney splash art, disney color palette, disney renaissance film, disney pixar movie still, disney art style, disney concept art :: nixri, wonderful compositions, pixar, disney concept artists, 2d character design',
    'Dystopian': '{prompt}, cifi world, cybernetic civilizations, peter gric and dan mumford,   brutalist dark futuristic, dystopian brutalist atmosphere, dark dystopian world, cinematic 8k, end of the world, doomsday',
    'Elven': '{prompt}, elven lifestyle, photoreal, realistic, 32k quality, crafted by Elves and engraved in copper, elven fantasy land, hyper detailed',
    'Euphoric': '{prompt}, digital illustration, style of charlie bowater, dreamy colorful cyberpunk colors, euphoric fantasy, epic dreamlike fantasy, beautiful oil matte painting, 8k fantasy art, fantasy art, jessica rossier color scheme, dreamlike diffusion',
    'Extra-terrestrial': '{prompt}, deepdream cosmic, painting by android jones, cosmic entity, humanoid creature, james jean soft light 4 k, sci fi, extra terrestrial, cinematic',
    'Fantasy': '{prompt}, fantasy matte painting, ( ( thomas kinkade ) ), high exposure, highly detailed, tim white, michael whelan',
    'Firebender': '{prompt}, fire elements, fantasy, fire, lava, striking. A majestic composition with fire elements, fire and ashes surrounding, highly detailed and realistic, cinematic lighting',
    'Forestpunk': '{prompt}, forestpunk, vibrant, HDRI, organic motifs and pollen in the air, bold vibrant colors and textures, spectacular sparkling rays, photorealistic quality with Hasselblad',
    'Futuristic': '{prompt}, futuristic, elegant atmosphere, glowing lights, highly detailed, digital painting, artstation, concept art, smooth sharp focus, illustration, mars ravelo, gereg rutkowski',
    'GTA': '{prompt}, gta iv art style, gta art,  gta loading screen art, gta chinatowon art style, gta 5 loading screen poster, grand theft auto 5, grand theft auto video game',
    'Glass Art': '{prompt}, inside glass ball, translucent sphere, cgsociety 9, glass orb, behance, polished, beautiful digital artwork, exquisite digital art, in a short round glass vase, octane render',
    'Glitch': '{prompt}, glitchwave, vaporwave pixel sorting, ((glitch art)), vektroid, glitch art aesthetic, psychedelic glitch art, glitch outline',
    'Gothic': '{prompt}, goth lifestyle, dark goth, grunge, cinematic photography, dramatic dark scenery, dark ambient beautiful',
    'Graffiti': '{prompt}, graffiti background, colorful graffiti, graffiti art style, colorful mural, ravi supa, symbolic mural, juxtapoz, pablo picasso, street art',
    'Halloween': '{prompt}, vibrant colors, halloween night, spooky aesthetic, creepy vibes, by Anne Stokes, digital painting style, illustration, bewitching, halloween, in a halloween style, dark theme, fearful atmosphere, supernatural, vibrant colors',
    'Haunted': '{prompt}, horror cgi 4 k, scary color art in 4 k, horror movie cinematography, insidious, la llorona, still from animated horror movie, film still from horror movie, haunted, eerie, unsettling, creepy',
    'Icon': '{prompt}, single vector graphics icon, ios icon, smooth shape, vector',
    'Illustration': '{prompt}, minimalistic vector art, illustrative style, style of ian hubert, style of gilles beloeil, inspired by Hsiao-Ron Cheng, style of jonathan solter, style of alexandre chaudret, by Echo Chernik',
    'Impressionism': '{prompt}, impressionism+++ , impressionist painting, style of claude monet, by Blanche Hoschedé Monet, impressionism and expressionism, impressionist art, monet painting',
    'Ink': '{prompt}, Black Ink, Hand drawn, Minimal art, artstation, artgem, monochrome',
    'Interior': '{prompt}, modern architecture by makoto shinkai, ilya kuvshinov, lois van baarle, rossdraws and frank lloyd wright',
    'Japanese Art': '{prompt}, Ukiyoe, illustration, muted colors',
    'Kawaii Chibi': '{prompt}, kawaii chibi romance, fantasy, illustration, Colorful idyllic cheerful, Kawaii Chibi inspired',
    'Knolling Case': '{prompt}, in  square glass case,  glass cube, glowing, knolling case, ash thorp, studio background,  desktopography, cgsociety 9,  cgsociety, mind-bending digital art',
    'Landscape': '{prompt}, landscape 4k, beautiful landscapes, nature wallpaper, 8k photography',
    'Logo': '{prompt}, creative logo, unique logo, visual identity, geometric type, graphic design, logotype design, brand identity, vector based, trendy typography, best of behance',
    'Macro Photography': '{prompt}, macro photography, award winning macro photography, depth of field, extreme closeup, 8k hd, focused',
    'Marble': '{prompt}, in greek marble style, classical antiquities, ancient greek classical ancient greek art, marble art, realistic, cinematic',
    'Medieval': '{prompt}, movie still from game of thrones, powerful fantasy epic, middle ages, olden times, roman empire, 1400 ce, highly detailed background, cinematic lighting, 8k render, high quality, bright colours',
    'Minecraft': '{prompt}, minecraft build, style of minecraft, pixel style, 8 bit, epic, cinematic, screenshot from minecraft, detailed natural lighting, minecraft gameplay, mojang,  minecraft mods, minecraft in real life,  blocky like minecraft',
    'Minimalism': '{prompt}, minimalism++ , minimal art, minimal aesthetic, minimal design, modern minimalism, minimal color palette, beautiful art, minimal vibes',
    'Mystical': '{prompt}, fireflies, deep focus, d&d, fantasy, intricate, elegant, highly detailed, digital painting, artstation, concept art, matte, sharp focus, illustration, hearthstrom, gereg rutkowski, alphonse mucha, andreas rocha',
    'Neo fauvism': '{prompt}, neo-fauvism painting, neo-fauvism movement, digital illustration, poster art, cgsociety saturated colors, fauvist',
    'Neon': '{prompt}, neon art style, night time dark with neon colors, blue neon lighting, violet and aqua neon lights, blacklight neon colors, rococo cyber neon lighting',
    'Origami': '{prompt} polygonal art, layered paper art, paper origami, wonderful compositions, folded geometry, paper craft, made from paper',
    'Painting': '{prompt}, atmospheric dreamscape painting, by Mac Conner, vibrant gouache painting scenery, vibrant painting, vivid painting, a beautiful painting, dream scenery art, instagram art, psychedelic painting, lofi art, bright art',
    'Palette Knife': '{prompt}, detailed impasto brush strokes,  detail acrylic palette knife, thick impasto technique,  palette knife, vibrant 8k colors',
    'PaperCut Style': '{prompt}, layered paper art, paper modeling art, paper craft, paper art, papercraft, paper cutout, paper cut out collage artwork, paper cut art',
    'Pattern': '{prompt} seamless pattern, ((repetitive pattern)), pattern design, background image, wallpaper,  colorful, decorated, flat design',
    'Picaso': '{prompt}, painting, by pablo picaso, cubism',
    'Pixel Art': '{prompt}, one pixel brush, pixelart, colorful pixel art',
    'Polaroid': '{prompt}, old polaroid, 35mm',
    'Poly Art': '{prompt}, low poly, artstation, studio lightning, stainless steel, grey color scheme',
    'Pop Art': '{prompt}, pop art painting, detailed patterns pop art, silkscreen pop art, pop art poster, roy lichtenstein style',
    'Pop Art II': '{prompt}, style of shepherd fairey, (Andy Warhol art style), silkscreen pop art, martin ansin artwork, high contrast illustrations, lowbrow pop art style, trending on artstatioin, vector style',
    'Poster Art': '{prompt}, album art, Poster, layout, typography, logo, risography, ghibili, simon stalenhag, insane detail, artstation, 8k',
    'Product Photography': '{prompt}, product photo studio lighting,  high detail product photo, product photography, commercial product photography, realistic, light,  8k, award winning product photography, professional closeup',
    'Psychedelic': '{prompt}, psychedelic painting, psychedelic dripping colors, colorful detailed projections, android jones and chris dyer, psychedelic vibrant colors, intricate psychedelic patterns, psychedelic visuals, hallucinatory art',
    'Rainbow': '{prompt}, intricate rainbow environment, rainbow bg, from lorax movie, pixar color palette, volumetric rainbow lighting, gorgeous digital painting, 8k cinematic',
    'Render': '{prompt}, isometric, polaroid octane render, 3 d render 1 5 0 mm lens, keyshot product render, rendered, keyshot product render pinterest, 3 d product render, 3 d cgi render, 3d cgi render, ultra wide angle isometric view',
    'Rennaisance': '{prompt}, renaissance period, neo-classical painting, italian renaissance workshop, pittura metafisica, raphael high renaissance, ancient roman painting, michelangelo painting, Leonardo da Vinci, italian renaissance architecture',
    'Retro': '{prompt}, retro futuristic illustration, featured on illustrationx, art deco illustration, beautiful retro art, stylized digital illustration, highly detailed vector art, ( ( mads berg ) ), automotive design art, epic smooth illustration, by mads berg, stylized illustration, ash thorp khyzyl saleem, clean vector art',
    'Retrowave': '{prompt}, Illustration, retrowave art, noen light, retro, digital art, trending on artstation',
    'Rococco': '{prompt}, francois boucher oil painting, rococco style,  rococco lifestyle, a flemish Baroque, by Karel Dujardin, vintage look, cinematic hazy lighting',
    'Salvador Dali': '{prompt}, Painting, by salvador dali, allegory, surrealism, religious art, genre painting, portrait, painter, still life',
    'Samurai': '{prompt}, samurai lifesyle, miyamoto musashi, Japanese art, ancient japanese samurai, feudal japan art, feudal japan art',
    'Scatter': '{prompt}, breaking pieces, exploding pieces, shattering pieces,  disintegration, contemporary digital art, inspired by Dan Hillier, inspired by Igor Morski, dramatic digital art, behance art, cgsociety 9, 3d advanced digital art, mind-bending digital art, disintegrating',
    'Shamrock Fantasy': '{prompt}, shamrock fantasy, fantasy, vivid colors, grapevine, celtic fantasy art, lucky clovers, dreamlike atmosphere, captivating details, soft light and vivid colors',
    'Sketch': '{prompt}, pencil, hand drawn, sketch, on paper',
    'Stained Glass': '{prompt} intricate wiccan spectrum, stained glass art, vividly beautiful colors, beautiful stained glass window, colorful image, intricate stained glass triptych, gothic stained glass style, stained glass window!!!',
    'Steampunk': '{prompt}, steampunk, stylized digital illustration, sharp focus, elegant, intricate, digital painting, artstation concept art, global illumination, ray tracing, advanced technology, chaykan howard, campion pascal, cooke darwin, davis jack, pink atmosphere',
    'Sticker': '{prompt}, sticker, sticker art, symmetrical sticker design, sticker - art, sticker illustration, die - cut sticker',
    'Studio Ghibli': '{prompt} by Hayao Mayazaki, Studio Ghibli, Studio Ghibli Style, Ghibli Style art, Ghibli Style characters,  cartoon style, beautifully rendered and expressive rich colors, vibrant pastel colors, imaginative and fantastical landscapes, sharp attention to detail, realism and a strong sense of nostalgia and warmth, sharp attention to small details and textures, fantastical creatures, settings, depth and emotions emphasized and accentuated by lighting and shading, extremely high quality, incredibly high finite definition, high resolution, hand-drawn and cel animation techniques, anime, 4k',
    'Surrealism': '{prompt}, salvador dali painting, highly detailed surrealist art, surrealist conceptual art,  masterpiece surrealism, surreal architecture, surrealistic digital artwork, whimsical surrealism, bizarre art',
    'Tattoo': '{prompt}, tattoo design, tattoo designs++ , black ink tattoo, line art, extraordinary designs, artistic tattoos, black and white tattoo, impressive, graphic illustrations, tattoo on skin, creative designs, vibrant colors, unique tattoos',
    'Valentines Day': '{prompt}, valentines Day, love, pink and red theme, Valentine aesthetic, roses, chocolates, love in the air, vibrant colors, hyper-realistic, creative artwork',
    'Van Gogh': '{prompt}, painting, by van gogh',
    'Vibrant': '{prompt}, Psychedelic, water colors spots, vibrant color scheme, highly detailed, romanticism style, cinematic, artstation, greg rutkowski',
    'Vibrant Viking': '{prompt}, Viking era, digital painting, pop of colour, forest, paint splatter, flowing colors, Background of lush forest and earthy tones, Artistic representation of movement and atmosphere',
    'Waterbender': '{prompt} water elements, fantasy, water, exotic, A majestic composition with water elements, waterfall, lush moss and exotic flowers, highly detailed and realistic, dynamic lighting',
    'Woolitize': '{prompt} cute! c4d, made out of wool, volumetric wool felting, wool felting art, houdini sidefx, rendered in arnold, soft smooth lighting, soft pastel colors',
}